// security-dashboard-vue/src/components/networks/nodes/PersonNode.vue
<template>
  <div class="person-node node">
    <Handle id="a" type="target" :position="Position.Top" :is-connectable="isConnectable" />
    <div class="node-content">
      <div class="node-header person">人员</div>
      <div class="node-label">{{ data.label }}</div>
      <div class="risk-score">风险评分: {{ data.riskScore ?? 'N/A' }}</div>
      <div class="risk-level">风险等级: {{ data.riskLevel ?? 'N/A' }}</div>
    </div>
    <Handle id="b" type="source" :position="Position.Bottom" :is-connectable="isConnectable" />
  </div>
</template>

<script setup lang="ts">
import type { NodeData } from '@/types/flow'
import { Handle, Position } from '@vue-flow/core'

interface PersonNodeProps {
  data: NodeData
  isConnectable?: boolean
}

const props = defineProps<PersonNodeProps>()
const isConnectable = props.isConnectable ?? true
</script>

<style>
/* Styles are global */
</style>

// security-dashboard/src/components/networks/nodes/PersonNode.tsx
import React from 'react';
import { Handle, Position } from 'reactflow';
import './nodes.css';

interface PersonNodeProps {
  data: {
    label: string;
    riskScore: number;
    riskLevel: string;
  };
  isConnectable: boolean;
}

const PersonNode: React.FC<PersonNodeProps> = ({ data, isConnectable }) => {
  return (
    <div className="person-node node">
      <Handle
        type="target"
        position={Position.Top}
        isConnectable={isConnectable}
      />
      <div className="node-content">
        <div className="node-header person">人员</div>
        <div className="node-label">{data.label}</div>
        <div className="risk-score">风险评分: {data.riskScore}</div>
        <div className="risk-level">风险等级: {data.riskLevel}</div>
      </div>
      <Handle
        type="source"
        position={Position.Bottom}
        isConnectable={isConnectable}
      />
    </div>
  );
};

export default PersonNode;
