// security-dashboard/src/pages/DataAssetMonitoring.tsx
import React from 'react';
import { ResourceFlowChart, ResourceFlowLegend } from '../components/networks';
import LineChart from '../components/charts/LineChart';
import { RiskTag, CapabilityTag, CustomTooltip } from '../components/tags/index';
import { StatisticCard, RankingCard, TableTopCard } from '../components/cards';
import { 
  assetStats, 
  riskResourceData, 
  highRiskUserData, 
  storageRiskResourceData, 
  lackProtectionResourceData,
  riskTrendData
} from '../data/securityMonitoringData';
import {
  storageRiskResourceTableData,
  protectionLackResourceTableData,
  highRiskUserTableData
} from '../data/tableTopData';
// 导入资源流图的模拟数据
import resourceFlowData from '../data/mock/network/resourceFlowData';

/**
 * 数据资产监测页面
 * 
 * 此页面监控和展示数据资产的安全防护情况，包括风险资源监控、防护能力评估等。
 * 
 * 主要区域：
 * - 上部分：
 *   - 左侧：访问关系图及数据资源数、数据分类数、数据分级数统计
 *   - 右侧：上下布局
 *     - 上：风险最多数据资源TOP
 *     - 下：高敏数据使用风险最多人员TOP
 * - 下部分：
 *   - 左侧：左右布局
 *     - 左：存在存储风险的数据资源TOP
 *     - 右：存在防护能力缺失的数据资源TOP
 *   - 右侧：最常发生的风险类型趋势
 * 
 * 更新记录：
 * - 2024-07-25: 新增TableTopCard组件，支持表格式和条形图展示数据，更符合设计图样式
 * - 2024-07-24: 更新TOP排行榜组件，使用实际数据量显示总计数，将"更多"改为按钮并支持弹窗展示完整数据
 * - 2024-07-24: 将节点详情面板集成到ResourceFlowChart组件中，移除冗余代码
 * - 2024-07-23: 提取可复用组件，优化页面布局和交互体验
 * - 2024-07-18: 根据UI设计图优化页面布局，调整为上下分区，改善视觉效果和信息结构
 * - 2024-06-18: 规范文件名为 DataAssetMonitoring.tsx（原 SecurityMonitoring.tsx）
 * - 2024-06-16: 优化数据资产防护监测大屏，添加ResourceFlowChart组件，创建标签组件目录和相关组件
 */
const DataAssetMonitoring: React.FC = () => {
  // 处理节点点击，仅用于日志记录或其他操作，不再管理选中状态
  const handleNodeClick = (node: any) => {
    console.log('Node clicked in parent component:', node);
  };

  // 处理边点击，仅用于日志记录或其他操作，不再管理选中状态
  const handleEdgeClick = (edge: any) => {
    console.log('Edge clicked in parent component:', edge);
  };

  // 处理排行榜项点击
  const handleRankingItemClick = (item: any) => {
    console.log('Ranking item clicked:', item);
  };

  // 获取包含异常连接的数据集，用于展示更丰富的资源访问关系
  const { nodes, edges } = resourceFlowData.withAbnormal;

  return (
    <div className="p-4 bg-gray-100 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {/* 页面标题区域 */}
        <div className="mb-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-800">数据资产防护监测</h1>
          <div className="text-sm text-gray-500">
            最后更新: {new Date().toLocaleString()}
          </div>
        </div>
        
        {/* 上部分内容 - 左右布局 */}
        <div className="grid grid-cols-12 gap-4 mb-4" style={{ height: '420px' }}>
          {/* 左侧 - 访问关系图及数据统计 */}
          <div className="col-span-8 flex flex-col h-full overflow-hidden">
            <div className="grid grid-cols-3 gap-4 mb-4 flex-none">
              {assetStats.map((stat, index) => (
                <StatisticCard
                  key={index}
                  label={stat.label}
                  value={stat.value}
                  className="bg-white shadow-sm border border-gray-100 rounded-lg"
                />
              ))}
            </div>
            
            {/* 资源访问关系图 */}
            <div className="bg-white rounded-lg shadow flex-1 flex flex-col overflow-hidden min-h-0">
              <div className="p-3 flex flex-col h-full">
                {/* 说明信息区域 */}
                <div className="flex-none border-b border-gray-100 pb-2 mb-2 flex items-center">
                  <svg className="w-4 h-4 text-blue-500 flex-shrink-0" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <span className="text-blue-500 font-medium text-xs ml-1">资源链路：</span>
                  <span className="text-gray-600 text-xs ml-1">
                    涉及用户、任务、应用、服务、数据资源，区分风险/无风险连接，悬浮可查看详情
                  </span>
                </div>
                
                {/* 资源流程图 */}
                <div className="flex-1 min-h-0 border border-gray-100 rounded-md">
                  <ResourceFlowChart 
                    initialNodes={nodes}
                    initialEdges={edges}
                    onNodeClick={handleNodeClick}
                    onEdgeClick={handleEdgeClick}
                    showControls={true}
                    fitView={true}
                  />
                </div>
                
                {/* 图例说明 */}
                <div className="flex-none mt-2 pt-2 border-t border-gray-100">
                  <ResourceFlowLegend />
                </div>
              </div>
            </div>
          </div>

          {/* 右侧 - 排行榜区域 */}
          <div className="col-span-4 flex flex-col h-full overflow-hidden">
            {/* 风险最多数据资源TOP */}
            <div className="flex-none" style={{ height: '45%' }}>
              <TableTopCard
                title="风险最多数据资源TOP"
                data={storageRiskResourceTableData}
                columns={[
                  { key: 'name', title: '资源名称' },
                  { key: 'riskValue', title: '风险', align: 'right' }
                ]}
                progressBarField="riskValue"
                onItemClick={handleRankingItemClick}
                className="h-full"
                maxItems={5}
              />
            </div>
            
            {/* 高风险数据使用风险最多人TOP */}
            <div className="flex-none mt-4" style={{ height: '52%' }}>
              <TableTopCard
                title="高敏数据使用风险最多人TOP"
                data={highRiskUserTableData}
                columns={[
                  { key: 'name', title: '姓名' },
                  { key: 'threatValue', title: '威胁数', align: 'right' }
                ]}
                progressBarField="threatValue"
                onItemClick={handleRankingItemClick}
                className="h-full"
                maxItems={8}
              />
            </div>
          </div>
        </div>
        
        {/* 下部分内容 - 左右布局 */}
        <div className="grid grid-cols-12 gap-4" style={{ height: '360px' }}>
          {/* 左侧 - 存储风险和防护能力缺失的TOP榜单 */}
          <div className="col-span-6 grid grid-cols-2 gap-4">
            {/* 存在存储风险的数据资源TOP */}
            <TableTopCard
              title="存在存储风险的数据资源TOP"
              data={storageRiskResourceTableData}
              columns={[
                { key: 'name', title: '资源名称' },
                { 
                  key: 'risk', 
                  title: '风险', 
                  render: (value) => (
                    <div>
                      {Array.isArray(value) && value.map((tag, idx) => (
                        <RiskTag key={idx} text={tag} />
                      ))}
                    </div>
                  )
                }
              ]}
              showProgressBar={false}
              onItemClick={handleRankingItemClick}
              className="h-full shadow"
              maxItems={7}
            />
            
            {/* 存在防护能力缺失的数据资源TOP */}
            <TableTopCard
              title="存在防护能力缺失的数据资源TOP"
              data={protectionLackResourceTableData}
              columns={[
                { key: 'name', title: '资源名称' },
                { 
                  key: 'protection', 
                  title: '防护能力', 
                  render: (value) => (
                    <div>
                      <CapabilityTag text={value} />
                    </div>
                  )
                }
              ]}
              showProgressBar={false}
              onItemClick={handleRankingItemClick}
              className="h-full shadow"
              maxItems={7}
            />
          </div>
          
          {/* 右侧 - 风险类型趋势图 */}
          <div className="col-span-6 bg-white rounded-lg shadow p-4 flex flex-col h-full">
            <div className="border-b border-gray-200 pb-2 mb-3 flex justify-between items-center">
              <div className="text-base font-medium">最常发生的风险类型趋势</div>
              <div className="text-xs text-gray-500">时间范围: 今日</div>
            </div>
            <div className="flex-grow pb-6">
              <LineChart
                title=""
                xAxisData={riskTrendData.xAxis}
                series={riskTrendData.series}
                showLegend={true}
                legendPosition="top"
                height="100%"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DataAssetMonitoring;

// security-dashboard-vue/src/views/DataAssetMonitoring.vue
<template>
  <div class="p-4 bg-gray-100 min-h-screen">
    <div class="max-w-7xl mx-auto">
      <!-- 页面标题区域 -->
      <div class="mb-4 flex justify-between items-center">
        <h1 class="text-2xl font-bold text-gray-800">数据资产防护监测</h1>
        <div class="text-sm text-gray-500">最后更新: {{ currentTime }}</div>
      </div>

      <!-- 上部分内容 - 左右布局 -->
      <div class="grid grid-cols-12 gap-4 mb-4" style="height: 420px">
        <!-- 左侧 - 访问关系图及数据统计 -->
        <div class="col-span-8 flex flex-col h-full overflow-hidden">
          <div class="grid grid-cols-3 gap-4 mb-4 flex-none">
            <!-- StatisticCard: 待迁移 -->

            <StatisticCard
              v-for="(stat, index) in assetStats"
              :key="index"
              :label="stat.label"
              :value="stat.value"
              class="bg-white shadow-sm border border-gray-100 rounded-lg"
            />

            <!--
            <div
              v-for="(stat, index) in assetStats"
              :key="index"
              class="bg-white shadow-sm border border-gray-100 rounded-lg p-4"
            >
              <div class="text-sm text-gray-500">{{ stat.label }}</div>
              <div class="text-2xl font-semibold text-gray-800">{{ stat.value }}</div>
              <div class="text-red-500 text-xs">临时占位符: StatisticCard</div>
            </div>
            -->
          </div>

          <!-- 资源访问关系图 -->
          <div class="bg-white rounded-lg shadow flex-1 flex flex-col overflow-hidden min-h-0">
            <div class="p-3 flex flex-col h-full">
              <!-- 说明信息区域 -->
              <div class="flex-none border-b border-gray-100 pb-2 mb-2 flex items-center">
                <svg
                  class="w-4 h-4 text-blue-500 flex-shrink-0"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
                <span class="text-blue-500 font-medium text-xs ml-1">资源链路：</span>
                <span class="text-gray-600 text-xs ml-1">
                  涉及用户、任务、应用、服务、数据资源，区分风险/无风险连接，悬浮可查看详情
                </span>
              </div>

              <!-- 资源流程图: ResourceFlowChart 待迁移 -->
              <div class="flex-1 min-h-0 border border-gray-100 rounded-md">
                <ResourceFlowChart
                  :initialNodes="initialNodes"
                  :initialEdges="initialEdges"
                  @node-click="handleNodeClick"
                  @edge-click="handleEdgeClick"
                  :showControls="true"
                  :fitView="true"
                />
              </div>

              <!-- 图例说明: ResourceFlowLegend 待迁移 -->
              <div class="flex-none mt-2 pt-2 border-t border-gray-100">
                <!-- <ResourceFlowLegend /> -->
                <div class="text-center text-gray-400 text-sm">临时占位符: ResourceFlowLegend</div>
              </div>
            </div>
          </div>
        </div>

        <!-- 右侧 - 排行榜区域 -->
        <div class="col-span-4 flex flex-col h-full overflow-hidden">
          <!-- 风险最多数据资源TOP: TableTopCard 待迁移 -->
          <TableTopCard
            title="风险最多数据资源TOP"
            :data="storageRiskResourceTableData"
            :columns="topRiskResourceColumns"
            progressBarField="riskValue"
            @itemClick="handleRankingItemClick"
            class="h-full flex-none"
            style="height: 45%"
            :maxItems="5"
          />

          <!-- 高风险数据使用风险最多人TOP: TableTopCard 待迁移 -->
          <TableTopCard
            title="高敏数据使用风险最多人TOP"
            :data="highRiskUserTableData"
            :columns="topRiskUserColumns"
            progressBarField="threatValue"
            @itemClick="handleRankingItemClick"
            class="h-full flex-none mt-4"
            style="height: 52%"
            :maxItems="8"
          />
        </div>
      </div>

      <!-- 下部分内容 - 左右布局 -->
      <div class="grid grid-cols-12 gap-4" style="height: 360px">
        <!-- 左侧 - 存储风险和防护能力缺失的TOP榜单 -->
        <div class="col-span-6 grid grid-cols-2 gap-4">
          <!-- 存在存储风险的数据资源TOP: TableTopCard, RiskTag 待迁移 -->
          <TableTopCard
            title="存在存储风险的数据资源TOP"
            :data="storageRiskResourceTableData"
            :columns="storageRiskColumns"
            :showProgressBar="false"
            @itemClick="handleRankingItemClick"
            class="h-full shadow"
            :maxItems="7"
          />

          <!-- 存在防护能力缺失的数据资源TOP: TableTopCard, CapabilityTag 待迁移 -->
          <TableTopCard
            title="存在防护能力缺失的数据资源TOP"
            :data="protectionLackResourceTableData"
            :columns="protectionLackColumns"
            :showProgressBar="false"
            @itemClick="handleRankingItemClick"
            class="h-full shadow"
            :maxItems="7"
          />
        </div>

        <!-- 右侧 - 风险类型趋势图 -->
        <div class="col-span-6 bg-white rounded-lg shadow p-4 flex flex-col h-full">
          <div class="border-b border-gray-200 pb-2 mb-3 flex justify-between items-center">
            <div class="text-base font-medium">最常发生的风险类型趋势</div>
            <div class="text-xs text-gray-500">时间范围: 今日</div>
          </div>
          <div class="flex-grow pb-6 h-full">
            <LineChart
              title=""
              :xAxisData="riskTrendData.xAxis"
              :series="riskTrendData.series"
              :showLegend="true"
              legendPosition="top"
              height="100%"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Fragment, h, onMounted, ref } from 'vue'
// 导入模拟数据 - 假设在 src/data 目录下，并配置了 @ 别名
// import resourceFlowData from '@/data/mock/network/resourceFlowData'; // 只导入当前需要的数据
import ResourceFlowChart from '@/components/networks/ResourceFlowChart.vue'
import { resourceFlowData } from '@/data/mock/network/resourceFlowData'
import { assetStats, riskTrendData } from '@/data/securityMonitoringData' // 只导入当前需要的数据

// 待迁移组件占位符 - 实际迁移时需替换为真实组件导入
import StatisticCard from '@/components/cards/StatisticCard.vue'
// import ResourceFlowChart from '@/components/networks/ResourceFlowChart.vue';
// import ResourceFlowLegend from '@/components/networks/ResourceFlowLegend.vue';
import TableTopCard from '@/components/cards/TableTopCard.vue'
import CapabilityTag from '@/components/tags/CapabilityTag.vue'
import RiskTag from '@/components/tags/RiskTag.vue'

// 导入其他需要的组件
import {
  highRiskUserTableData,
  protectionLackResourceTableData,
  storageRiskResourceTableData,
} from '@/data/tableTopData'

// --- State ---
const currentTime = ref(new Date().toLocaleString())

// ResourceFlowChart Data - Uncomment
const { nodes: initialNodes, edges: initialEdges } = resourceFlowData.withAbnormal

// --- Lifecycle Hooks ---
onMounted(() => {
  // 可以设置定时器更新时间，如果需要实时更新的话
  // setInterval(() => {
  //   currentTime.value = new Date().toLocaleString();
  // }, 1000);
})

// --- Methods ---
// 假设从 @vue-flow/core 导入 Node 和 Edge 类型
import type { Edge, Node } from '@vue-flow/core'
// 假设我们定义或导入了 RankingItem 类型
// import type { RankingItem } from '@/types/ranking'; // 示例路径

// --- 假设的 RankingItem 类型定义 (如果不存在则需要创建) ---
interface RankingItem {
  id: number | string
  name: string
  // ... 其他属性
}
// ---

// Uncomment node/edge click handlers
// 使用导入的类型， Node/Edge 可以接受泛型参数指定具体数据类型，例如 Node<MyNodeData>
const handleNodeClick = (node: Node) => {
  console.log('Node clicked in Vue component:', node)
}

const handleEdgeClick = (edge: Edge) => {
  console.log('Edge clicked in Vue component:', edge)
}

const handleRankingItemClick = (item: RankingItem) => {
  // 使用具体的 RankingItem 类型
  console.log('Ranking item clicked:', item)
}

// --- Column Definitions with Vue Render Functions ---

const storageRiskColumns = [
  { key: 'name', title: '资源名称' },
  {
    key: 'risk',
    title: '风险',
    render: (value: unknown) => {
      // 使用类型守卫 Array.isArray 并检查元素类型
      if (Array.isArray(value) && value.every((item) => typeof item === 'string')) {
        // 显式创建一个 string[] 类型的变量
        const stringArray: string[] = value
        // 使用这个类型明确的变量
        return h(
          Fragment,
          stringArray.map(
            (
              tagText: string,
              idx: number, // 使用 stringArray
            ) => h(RiskTag, { key: idx, text: tagText, class: 'mr-1 mb-1' }),
          ),
        )
      }
      // Return an empty Fragment if not an array or no tags
      return h(Fragment)
    },
  },
]

const protectionLackColumns = [
  { key: 'name', title: '资源名称' },
  {
    key: 'protection',
    title: '防护能力',
    render: (value: unknown) => {
      // 检查 value 是否为 string，如果不是，提供一个默认值或进行转换
      const textValue = typeof value === 'string' ? value : '' // 如果不是字符串，则使用空字符串
      // 或者进行更复杂的处理，例如: const textValue = String(value);
      return h(CapabilityTag, { text: textValue }) // <--- 传递处理后的 textValue
    },
  },
]

const topRiskResourceColumns = [
  { key: 'name', title: '资源名称' },
  { key: 'riskValue', title: '风险', align: 'right' as const },
]

const topRiskUserColumns = [
  { key: 'name', title: '姓名' },
  { key: 'threatValue', title: '威胁数', align: 'right' as const },
]
</script>

<style scoped>
/* 如果需要添加特定于此组件的样式，可以在这里添加 */
/* Tailwind CSS 类名已在模板中直接使用 */
.h-full {
  height: 100%;
}
.min-h-screen {
  min-height: 100vh;
}
/* 可以根据需要覆盖或添加更多样式 */
</style>
