// security-dashboard-vue/src/components/charts/CircularProgress.vue
<template>
  <div
    :class="[
      'bg-white rounded-lg shadow p-2 flex',
      layout === 'horizontal' ? 'items-center justify-between' : 'flex-col items-center',
    ]"
  >
    <!-- Text Area -->
    <div :class="[layout === 'horizontal' ? 'mr-2 text-left' : 'mb-1 text-center']">
      <div :class="['font-medium text-gray-700', size === 'small' ? 'text-xs' : 'text-sm']">
        {{ title }}
      </div>
      <!-- Description (optional) -->
      <!-- <div
        v-if="description"
        :class="[
          'text-gray-500',
          size === 'small' ? 'text-xxs' : 'text-xs'
        ]"
      >
        {{ description }}
      </div> -->
    </div>

    <!-- Chart Area -->
    <div class="relative" :style="chartStyle">
      <v-chart
        v-if="option"
        :option="option"
        autoresize
        :style="{ height: '100%', width: '100%' }"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { GaugeChart } from 'echarts/charts'
import { LegendComponent, TitleComponent, TooltipComponent } from 'echarts/components'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { computed } from 'vue'
import VChart from 'vue-echarts'

// Register necessary ECharts components
use([CanvasRenderer, GaugeChart, TitleComponent, TooltipComponent, LegendComponent])

interface CircularProgressProps {
  percentage: number
  title: string
  color?: string
  description?: string // Not used currently
  layout?: 'horizontal' | 'vertical'
  size?: 'small' | 'medium' | 'large'
}

const props = withDefaults(defineProps<CircularProgressProps>(), {
  color: '#3b82f6',
  layout: 'vertical',
  size: 'medium',
})

// Generate gradient color
const getGradientColor = (baseColor: string) => {
  return {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [
      { offset: 0, color: baseColor }, // Lighter color can be adjusted if needed
      { offset: 1, color: baseColor },
    ],
  }
}

// Determine chart dimensions based on size
const chartStyle = computed(() => {
  switch (props.size) {
    case 'small':
      return { width: '50px', height: '50px', minWidth: '50px' } // Adjusted size slightly
    case 'large':
      return { width: '90px', height: '90px', minWidth: '90px' }
    case 'medium':
    default:
      return { width: '70px', height: '70px', minWidth: '70px' }
  }
})

// Calculate font size based on chart size
const detailFontSize = computed(() => {
  switch (props.size) {
    case 'small':
      return 12
    case 'large':
      return 18
    case 'medium':
    default:
      return 14
  }
})

// Compute ECharts option
const option = computed(() => ({
  series: [
    {
      type: 'gauge',
      startAngle: 90,
      endAngle: -270,
      radius: '95%', // Slightly larger radius for tighter look
      center: ['50%', '50%'],
      pointer: { show: false },
      progress: {
        show: true,
        overlap: false,
        roundCap: true,
        clip: false,
        itemStyle: {
          color: getGradientColor(props.color),
        },
        width: props.size === 'small' ? 6 : props.size === 'large' ? 10 : 8, // Adjust thickness based on size
      },
      axisLine: {
        lineStyle: {
          width: props.size === 'small' ? 6 : props.size === 'large' ? 10 : 8, // Match progress width
          color: [[1, '#e6ebf8']],
        },
      },
      splitLine: { show: false },
      axisTick: { show: false },
      axisLabel: { show: false },
      data: [
        {
          value: props.percentage,
          // name: `${props.percentage}%`, // Use detail formatter instead of name
          title: { show: false }, // Hide the default title
          detail: {
            valueAnimation: true,
            offsetCenter: [0, 0],
            fontSize: detailFontSize.value,
            fontWeight: 'bold',
            formatter: '{value}%',
            color: props.color,
          },
        },
      ],
      title: { show: false }, // Hide series title
      detail: {
        show: true, // Ensure detail (percentage text) is shown
        // Settings moved inside data.detail for better control
      },
    },
  ],
}))
</script>

<style scoped>
/* Add any component-specific styles here if needed */
/* Example for very small text if needed */
/* .text-xxs { font-size: 0.625rem; line-height: 0.875rem; } */
</style>

// security-dashboard/src/components/charts/CircularProgress.tsx
import React from 'react';
import ReactECharts from 'echarts-for-react';

interface CircularProgressProps {
  percentage: number;
  title: string;
  color?: string;
  description?: string;
  layout?: 'horizontal' | 'vertical';
  size?: 'small' | 'medium' | 'large';
}

/**
 * 环形进度图组件
 * 
 * 可配置为水平布局（左侧文字，右侧图表）或垂直布局（上方文字，下方图表）
 * 支持不同尺寸的显示模式，百分比数字默认显示在环形图中间
 * 
 * 更新记录：
 * - 2024-05-01: 添加水平布局支持，增强样式定制能力
 */
const CircularProgress: React.FC<CircularProgressProps> = ({ 
  percentage, 
  title,
  color = '#3b82f6',
  description = '占比',
  layout = 'vertical',
  size = 'medium'
}) => {
  // 生成渐变色
  const getGradientColor = () => {
    // 基于传入的color创建渐变色
    const baseColor = color;
    const lighterColor = color; // 如果需要可以调整为更亮的颜色
    
    return {
      type: 'linear',
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [{
        offset: 0, color: lighterColor
      }, {
        offset: 1, color: baseColor
      }]
    };
  };

  // 根据size属性确定图表尺寸
  const getChartSize = () => {
    switch(size) {
      case 'small': return { width: '60px', height: '60px' };
      case 'large': return { width: '100px', height: '100px' };
      case 'medium':
      default: return { width: '80px', height: '80px' };
    }
  };

  const { width, height } = getChartSize();

  // 更新ECharts选项，添加中央显示百分比功能
  const option = {
    series: [
      {
        type: 'gauge',
        startAngle: 90,
        endAngle: -270,
        radius: '90%', // 调整环形大小，为中央文字留出空间
        center: ['50%', '50%'],
        pointer: {
          show: false
        },
        progress: {
          show: true,
          overlap: false,
          roundCap: true,
          clip: false,
          itemStyle: {
            color: getGradientColor()
          }
        },
        axisLine: {
          lineStyle: {
            width: 10,
            color: [[1, '#e6ebf8']]
          }
        },
        splitLine: {
          show: false,
        },
        axisTick: {
          show: false
        },
        axisLabel: {
          show: false
        },
        data: [
          {
            value: percentage,
            name: percentage + '%',
            title: {
              show: false
            },
            detail: {
              valueAnimation: true,
              offsetCenter: [0, 0],
              fontSize: 16,
              fontWeight: 'bold',
              formatter: '{value}%',
              color: color
            }
          }
        ],
        title: {
          show: false
        },
        detail: {
          show: true,
          fontSize: 20,
          fontWeight: 'bold',
          color: color
        }
      }
    ]
  };

  // 水平布局
  if (layout === 'horizontal') {
    return (
      <div className="p-4 bg-white border border-gray-100 rounded-lg flex items-center justify-between">
        <div className="flex flex-col mr-4">
          <div className="text-base font-medium text-gray-700">{title}</div>
          {/* <div className="text-xs text-gray-500 mt-1">{description}</div> */}
        </div>
        <div className="relative" style={{ width, height, minWidth: width }}>
          <ReactECharts 
            option={option} 
            style={{ height: '100%', width: '100%' }}
          />
          {/* 移除独立的百分比数字，已在图表内部显示 */}
        </div>
      </div>
    );
  }

  // 垂直布局（默认）
  return (
    <div className="p-4 bg-white border border-gray-100 rounded-lg flex flex-col items-center">
      <div className="text-sm text-gray-600 mb-2 text-center">{title}</div>
      {/* <div className="text-xs text-gray-400 mb-1">{description}</div> */}
      <div className="relative mb-2" style={{ width, height }}>
        <ReactECharts 
          option={option} 
          style={{ height: '100%', width: '100%' }}
        />
        {/* 移除独立的百分比数字，已在图表内部显示 */}
      </div>
    </div>
  );
};

export default CircularProgress;
